add_newline = false

format = "$time$username$directory$conda$git_branch$git_status$character"


[username]
show_always = true
format = "[$user]($style) "

[directory]
format = "[$path]($style) "
truncate_to_repo = true
truncation_length = 1
fish_style_pwd_dir_length = 1


[python]
disabled = false
format = "[$virtualenv]($style) "

[conda]
disabled = false
ignore_base = false
symbol = ""
format = "[$environment]($style) "

[ruby]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[package]
disabled = true

[git_status]
format = '[$ahead_behind]($style) '
disabled = false

[git_branch]
format = "[$branch]($style) "
symbol = ""

[character]
success_symbol = "❯ "
error_symbol = "❯ "

[time]
disabled = false
format = "[$time]($style) "
time_format = "%Y-%m-%d %H:%M:%S"

