if [ -x /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -x /usr/local/bin/brew ]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

if [ -f "$HOME/.zprofile.local" ]; then . "$HOME/.zprofile.local"; fi

if [ -f /opt/miniconda3/etc/profile.d/conda.sh ]; then
  . /opt/miniconda3/etc/profile.d/conda.sh
fi
