_CONDA_CANDIDATES=(
  "$HOME/miniconda3"
  "/opt/miniconda3"
  "/opt/anaconda3"
)

for _c in "${_CONDA_CANDIDATES[@]}"; do
  if [ -x "$_c/bin/conda" ]; then
    __conda_setup="$("$_c/bin/conda" 'shell.zsh' 'hook' 2>/dev/null)"
    if [ $? -eq 0 ]; then
      eval "$__conda_setup"
    else
      if [ -f "$_c/etc/profile.d/conda.sh" ]; then
        . "$_c/etc/profile.d/conda.sh"
      else
        export PATH="$_c/bin:$PATH"
      fi
    fi
    unset __conda_setup
    break
  fi
done
unset _CONDA_CANDIDATES _c

command -v brew >/dev/null 2>&1 && eval "$(brew shellenv)"

# ---- chruby (unified for ARM + Intel) ----
export RUBY_AUTO_VERSION=""
if [ -f /opt/homebrew/opt/chruby/share/chruby/chruby.sh ]; then
  source /opt/homebrew/opt/chruby/share/chruby/chruby.sh
  [ -f /opt/homebrew/opt/chruby/share/chruby/auto.sh ] && source /opt/homebrew/opt/chruby/share/chruby/auto.sh
elif [ -f /usr/local/opt/chruby/share/chruby/chruby.sh ]; then
  source /usr/local/opt/chruby/share/chruby/chruby.sh
  [ -f /usr/local/opt/chruby/share/chruby/auto.sh ] && source /usr/local/opt/chruby/share/chruby/auto.sh
fi

type chruby >/dev/null 2>&1 && chruby ruby-3.4.1

export PATH="$HOME/Documents/bin:$PATH"

command -v starship >/dev/null 2>&1 && eval "$(starship init zsh)"

arrive() {
  if [ -x "$HOME/Documents/SharedConfigs/bin/arrive" ]; then
    zsh "$HOME/Documents/SharedConfigs/bin/arrive"
  else
    zsh "$HOME/Documents/SharedConfigs/bin/arrive.sh"
  fi
  local rc=$?
  if [[ $rc -ne 0 ]]; then
    echo "arrive failed (exit $rc)"
    return $rc
  fi
  if [[ -f .uses-qmcpy ]] && command -v conda >/dev/null 2>&1; then
    eval "$(conda shell.zsh hook)"
    conda activate qmcpy
  fi
}

depart() {
  if [ -x "$HOME/Documents/SharedConfigs/bin/leave" ]; then
    zsh "$HOME/Documents/SharedConfigs/bin/leave"
  else
    zsh "$HOME/Documents/SharedConfigs/bin/leave.sh"
  fi
}
